restclient.productos.baseurl=http://localhost:8080/alumnos
server.port=8082    
# Internacionalización
spring.messages.encoding=UTF-8
# Ruta desde resources/nombre del fichero
spring.messages.basename=messages
## Ver logs detallados de todo el framework
logging.level.org.springframework=DEBUG
spring.mvc.hiddenmethod.filter.enabled=true

# Específicamente para el mapeo de URLs y vistas (muy útil para el 404)
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.view=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración optimizada para desarrollo
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Logging de SQL para debugging
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# Conexión a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/store_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=alumn-service