

/**
 * 
 * @author Alba Garcia Puerta
 * @version 1.0
 * @since 2025-12-08
 */

-- ========================
-- Tabla PROFESOR
-- ========================
CREATE TABLE PROFESOR (
    profesor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ========================
-- Tabla ALUMNO
-- ========================
CREATE TABLE ALUMNO (
    alumno_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    profesor_id BIGINT,
    FOREIGN KEY (profesor_id) REFERENCES PROFESOR(profesor_id) ON DELETE SET NULL
);

-- ========================
-- Tabla CABALLO
-- ========================
CREATE TABLE CABALLO (
    caballo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    edad INT,
    raza VARCHAR(50),
    alumno_id BIGINT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (alumno_id) REFERENCES ALUMNO(alumno_id) ON DELETE SET NULL
);

-- ========================
-- Tabla PISTA
-- ========================
CREATE TABLE PISTA (
    pista_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- ========================
-- Tabla CLASE
-- ========================
CREATE TABLE CLASE (
    clase_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    profesor_id BIGINT,
    alumno_id BIGINT,
    tipo ENUM('PRACTICA','TEORICA') NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (profesor_id) REFERENCES PROFESOR(profesor_id) ON DELETE SET NULL,
    FOREIGN KEY (alumno_id) REFERENCES ALUMNO(alumno_id) ON DELETE SET NULL
);

-- ========================
-- Tabla RESERVA
-- ========================
CREATE TABLE RESERVA (
    reserva_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL,
    clase_id BIGINT NOT NULL,
    pista_id BIGINT NOT NULL,
    caballo_id BIGINT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (alumno_id) REFERENCES ALUMNO(alumno_id) ON DELETE CASCADE,
    FOREIGN KEY (clase_id) REFERENCES CLASE(clase_id) ON DELETE CASCADE,
    FOREIGN KEY (pista_id) REFERENCES PISTA(pista_id) ON DELETE CASCADE,
    FOREIGN KEY (caballo_id) REFERENCES CABALLO(caballo_id) ON DELETE CASCADE
);

-- ========================
-- Tabla USUARIOS
-- ========================

CREATE TABLE USUARIOS (
    -- Clave Primaria
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    password VARCHAR(72) NOT NULL,
    role VARCHAR(100) NOT NULL
);


-- ========================
-- Secuencia PROFESOR
-- ========================
DROP SEQUENCE IF EXISTS PROFESOR_SEQ;
CREATE SEQUENCE PROFESOR_SEQ START WITH 100 INCREMENT BY 1;

-- ========================
-- Secuencia ALUMNO
-- ========================
DROP SEQUENCE IF EXISTS ALUMNO_SEQ;
CREATE SEQUENCE ALUMNO_SEQ START WITH 100 INCREMENT BY 1;

-- ========================
-- Secuencia CABALLO
-- ========================
DROP SEQUENCE IF EXISTS CABALLO_SEQ;
CREATE SEQUENCE CABALLO_SEQ START WITH 100 INCREMENT BY 1;

-- ========================
-- Secuencia PISTA
-- ========================
DROP SEQUENCE IF EXISTS PISTA_SEQ;
CREATE SEQUENCE PISTA_SEQ START WITH 100 INCREMENT BY 1;

-- ========================
-- Secuencia CLASE
-- ========================
DROP SEQUENCE IF EXISTS CLASE_SEQ;
CREATE SEQUENCE CLASE_SEQ START WITH 100 INCREMENT BY 1;

-- ========================
-- Secuencia RESERVA
-- ========================
DROP SEQUENCE IF EXISTS RESERVA_SEQ;
CREATE SEQUENCE RESERVA_SEQ START WITH 100 INCREMENT BY 1;
